In [1]:
import torch

In [3]:
tensor = torch.arange(12)

In [6]:
tensor_view = tensor.view(2,6)
tensor_reshape = tensor.reshape(2,6)

print(tensor_view)
print(tensor_reshape)

print(tensor_view.shape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
torch.Size([2, 6])


In [7]:
tensor.is_contiguous()

True

In [ ]:
tensor_reshape.is_contiguous()


True

In [10]:
tensor_view.is_contiguous()

True

In [11]:
inferred_shape = tensor.view(3,-1)
print(inferred_shape)
print(inferred_shape.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [12]:
tensor3d = torch.arange(24).reshape(2,3,4)
print(tensor3d)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [13]:
flattened = tensor3d.view(-1)
print(flattened)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])


In [14]:
flattened.is_contiguous()

True

## Non-Contiguous

In [15]:
tensor2d = torch.arange(24).reshape(12,2)
transpose_tensor = tensor2d.t()

In [17]:
transpose_tensor.is_contiguous()

False

In [18]:
error = transpose_tensor.reshape(6,4)

In [19]:
print(error)
print(error.shape)

tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [17, 19, 21, 23]])
torch.Size([6, 4])


In [20]:
contiguous = transpose_tensor.contiguous()
error = contiguous.view(6,4)

In [21]:
print(error)
print(error.shape)

tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [17, 19, 21, 23]])
torch.Size([6, 4])
