In [1]:
# data types for tensors
'''
* floating -- for most deep learning tasks ---> float32, float64, float16
* integers - for categorical data and indices --> int32, int64, int8
* booleans - mask or logical operation
* Complex number - advanced computation --> complex64, complex128

memory consumption : float16 << float32 << float64
computation : lower precision will be faster on gpu
numberical precision : float64 is more precise than float32
'''

'\n* floating -- for most deep learning tasks ---> float32, float64, float16\n* integers - for categorical data and indices --> int32, int64, int8\n* booleans - mask or logical operation\n* Complex number - advanced computation --> complex64, complex128\n\nmemory consumption : float16 << float32 << float64\ncomputation : lower precision will be faster on gpu\nnumberical precision : float64 is more precise than float32\n'

In [2]:
import torch

In [3]:
default_tensor = torch.tensor([1.5, 2.5, 3.5])
print(default_tensor.dtype)

torch.float32


In [5]:
float_tensor = torch.tensor([1.5, 2.5, 3.5], dtype=torch.float64)
print(float_tensor.dtype)

torch.float64


In [4]:
int_tensor = torch.tensor([1.5, 2.5, 3.5], dtype=torch.int32)
print(int_tensor.dtype)
print(int_tensor)

torch.int32
tensor([1, 2, 3], dtype=torch.int32)


In [6]:
int_tensor = torch.tensor([1, 2, 3])
print(int_tensor.dtype)
print(int_tensor)

torch.int64
tensor([1, 2, 3])


In [7]:
bool_tensor = torch.tensor([True, False, True], dtype=torch.bool)
print(bool_tensor.dtype)
print(bool_tensor)

torch.bool
tensor([ True, False,  True])


In [8]:
float_tensor = torch.tensor([1.5, 2.5, 3.5])
print(float_tensor.dtype)
print(float_tensor)

int_tensor = float_tensor.to(torch.int64)
print(int_tensor.dtype)
print(int_tensor)

int_tensor = torch.tensor([0,1,2,0, -1])
bool_tensor = int_tensor.to(torch.bool)
print(bool_tensor.dtype)
print(bool_tensor)

torch.float32
tensor([1.5000, 2.5000, 3.5000])
torch.int64
tensor([1, 2, 3])
torch.bool
tensor([False,  True,  True, False,  True])


### Impact of Data Type on memory

In [9]:
float32_tensor = torch.ones(1000, dtype=torch.float32)
float64_tensor = torch.ones(1000, dtype=torch.float64)

# tensor.element_size()
# element_size() --> gives you the size of one element in bytes
# nelement() --> gives the total number of elements in tensor

print(float32_tensor.element_size())
print(float32_tensor.nelement())
print("Memory used by float32 tensor : ", float32_tensor.element_size() * float32_tensor.nelement(), " bytes")
print("Memory used by float64 tensor : ", float64_tensor.element_size() * float64_tensor.nelement(), " bytes")

4
1000
Memory used by float32 tensor :  4000  bytes
Memory used by float64 tensor :  8000  bytes


In [ ]:
# float32 --> default for most NN models
# float64 --> high precision computation
# int32 --> general purpose integer
# int64 --> tensor indices
# int8, int16 --> reduce memory usage
# bool --> mask and logical operation
# float16 --> half precision of your default floating dtype, reduce memory usage
# complex64 --> advanced computation