## tensor manipulation

- reshaping
- slicing
- joining or splitting
- transposing and permuting dimension

In [1]:
import torch

In [2]:
# reshaping tensors
# reshape
# view

original_tensor = torch.arange(12)
print(original_tensor)
print(original_tensor.nelement())
print(original_tensor.ndim)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
12
1


In [3]:
# 2x6--> 12

reshaped_tensor = original_tensor.reshape(2,6)
print(reshaped_tensor)
print(reshaped_tensor.ndim)
print(reshaped_tensor.nelement())


tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
2
12


In [4]:
reshaped_tensor = original_tensor.reshape(3,4)
print(reshaped_tensor)
print(reshaped_tensor.ndim)
print(reshaped_tensor.nelement())

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
2
12


In [5]:
# view
print(original_tensor.is_contiguous())
flattened_tensor = original_tensor.view(-1)
print(flattened_tensor)

True
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


# Slicing

Extract specific portions of tensors


In [6]:
tensor_a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(tensor_a)
print(tensor_a.ndim)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2


In [7]:
print(tensor_a[0])

tensor([1, 2, 3])


In [8]:
tensor_a[:,2]

tensor([3, 6, 9])

In [9]:
print(tensor_a.shape)

torch.Size([3, 3])


In [10]:
sub_tensor = tensor_a[1:,1:]
print(sub_tensor.shape)
print(sub_tensor)

torch.Size([2, 2])
tensor([[5, 6],
        [8, 9]])
