## Matrix Aggregation

In [1]:
import torch

In [2]:
matrix = torch.tensor([[1., 2., 3.],
              [4., 5., 6.],
              [7., 8., 9.],])

print(matrix)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [3]:
print(matrix.sum())
print(matrix.min())
print(matrix.max())
print(matrix.median())
print(matrix.mean())

tensor(45.)
tensor(1.)
tensor(9.)
tensor(5.)
tensor(5.)


In [4]:
# dim=0 --> rows (column)
# dim=1 --> colmn (rows)

print(matrix.max(dim=0))
print(matrix.sum(dim=0))
print(matrix.sum(dim=1))

torch.return_types.max(
values=tensor([7., 8., 9.]),
indices=tensor([2, 2, 2]))
tensor([12., 15., 18.])
tensor([ 6., 15., 24.])


In [5]:
cumulative_sum = matrix.cumsum(dim=1)
print(cumulative_sum)

tensor([[ 1.,  3.,  6.],
        [ 4.,  9., 15.],
        [ 7., 15., 24.]])


In [6]:
cumulative_prod = matrix.cumprod(dim=0)
print(cumulative_prod)

tensor([[  1.,   2.,   3.],
        [  4.,  10.,  18.],
        [ 28.,  80., 162.]])


In [7]:
# advance aggregation

masked_matrix_sum = matrix[matrix>5].sum()
print(masked_matrix_sum)

tensor(30.)


In [8]:
matrix = torch.tensor([[1., 2., 3.],
              [4., 5., 6.],
              [7., 8., 9.],])

non_zero = matrix.nonzero()
print(non_zero)
print(non_zero.shape)
print(non_zero.size(0))

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 2],
        [2, 0],
        [2, 1],
        [2, 2]])
torch.Size([9, 2])
9


## Normalised Matrix

In [9]:
max_v = matrix.max()
min_v = matrix.min()
normalised_matrix = (matrix - min_v) / (max_v - min_v)

print(normalised_matrix)

tensor([[0.0000, 0.1250, 0.2500],
        [0.3750, 0.5000, 0.6250],
        [0.7500, 0.8750, 1.0000]])
